spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: {POSTGRES_USER}
    password: {POSTGRES_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
jpa:
  database-platform: org.hibernate.dialect.PostgresPlusDialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      default_schema: dops