spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://172.17.0.8:5432/dops
jpa:
  database-platform: org.hibernate.dialect.PostgresPlusDialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      default_schema: dops

server:
  port: 8080